server:
  port: 8080

spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/mydb?serverTimezone=UTC
    username: root
    password: vavavo97*
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
     oauth2:
       client:
         registration:
           kakao:
             client-id: dbda976eb054714809926c699703fc3b
             client-secret: IKdsMnzh7RZtKoub161cFADP8ASc6pml
             authorization-grant-type: authorization_code
             client-authentication-method: client_secret_post
             redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
             client-name: Kakao
           naver:
             client-id: 0hXy2isjmPP_8MICXjsZ
             client-secret: lpMGBLOWuv
             authorization-grant-type: authorization_code
             redirect-uri: "{baseUrl}/login/oauth2/code/naver"
             client-name: Naver
         provider:
           kakao:
             authorization-uri: https://kauth.kakao.com/oauth/authorize
             token-uri: https://kauth.kakao.com/oauth/token
             user-info-uri: https://kapi.kakao.com/v2/user/me
             user-name-attribute: id
           naver:
             authorization-uri: https://nid.naver.com/oauth2.0/authorize
             token-uri: https://nid.naver.com/oauth2.0/token
             user-info-uri: https://openapi.naver.com/v1/nid/me
             user-name-attribute: response
  jpa:
    database: MYSQL
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        storage_engine: innodb
        show_sql: true
        format_sql: true
        user_sql_comments: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 900000
  refresh-token-expiration: 1209600000
  header: Authorization
  prefix: Bearer

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind : TRACE

file:
  upload-dir: c:/bootDev/bootStudy/images/
---

spring:
  config:
    activate:
      on-profile: prod
file:
  upload-dir: /home/ubuntu/app/images/		
